apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
    - port: 80            # The port that will be exposed inside the cluster
      targetPort: 5000    # The port your Flask app is listening on
      nodePort: 30001     # The port that will be exposed on each Node
